[package]
name = "colorrs"
version = "0.1.0"
edition = "2024"
description = "A Rust CLI for outputting terminal colour test images"
authors = ["Emma Alexandria <emma.jellemabutler@gmail.com>"]

[dependencies]
clap = { version = "4.5.47", features = ["cargo"] }
wild = "2.2.1"
