pattern = """
{boldon}{redfbright}        ■      {boldon}{greenfbright}        ■      {boldon}{yellowfbright}        ■     {boldon}{bluefbright}         ■       {boldon}{purplefbright}       ■      {boldon}{cyanfbright}        ■   {reset}
{boldon}{redfbright}       ■■■     {boldon}{greenfbright}       ■■■     {boldon}{yellowfbright}       ■■■    {boldon}{bluefbright}        ■■■      {boldon}{purplefbright}      ■■■     {boldon}{cyanfbright}       ■■■  {reset}
{boldon}{redfbright}      ■■■■■    {boldon}{greenfbright}      ■■■■■    {boldon}{yellowfbright}      ■■■■■   {boldon}{bluefbright}       ■■■■■     {boldon}{purplefbright}     ■■■■■    {boldon}{cyanfbright}      ■■■■■ {reset}
{redf}     ■(   )■   {greenf}     ■(   )■   {yellowf}     ■(   )■   {bluef}     ■(   )■    {purplef}    ■(   )■   {cyanf}     ■(   )■   {reset}
{redf}    ■■■■ ■■■■  {greenf}    ■■■■ ■■■■  {yellowf}    ■■■■ ■■■■  {bluef}    ■■■■ ■■■■   {purplef}   ■■■■ ■■■■  {cyanf}    ■■■■ ■■■■  {reset}
{redf}   ■■       ■■ {greenf}   ■■       ■■ {yellowf}   ■■       ■■ {bluef}   ■■       ■■  {purplef}  ■■       ■■ {cyanf}   ■■       ■■ {reset}
"""


[colors]
boldon = "1"

redf = "31"
greenf = "32"
yellowf = "33"
bluef = "34"
purplef = "35"
cyanf = "36"

redfbright = "91"
greenfbright = "92"
yellowfbright = "93"
bluefbright = "94"
cyanfbright = "96"
purplefbright = "95"
